export const BAIRROS = [
  'Acácio Figueiredo',
  'Alto Branco',
  'Araxá',
  'Bela Vista',
  'Bodocongó',
  'Castelo Branco',
  'Catolé',
  'Centenário',
  'Centro',
  'Cidades',
  'Conceição',
  'Cruzeiro',
  'Cuités',
  'Dinamérica',
  'Distrito Industrial',
  'Estação Velha',
  'Itararé',
  'Jardim Continental',
  'Jardim Paulistano',
  'Jardim Quarenta',
  'Jardim Tavares',
  'Jeremias',
  'José Pinheiro',
  'Lauritzen',
  'Liberdade',
  'Louzeiro',
  'Malvinas',
  'Mirante',
  'Monte Castelo',
  'Monte Santo',
  'Nações',
  'Nova Brasília',
  'Novo Bodocongó',
  'Palmeira',
  'Pedregal',
  'Prata',
  'Presidente Médici',
  'Quarenta',
  'Ramadinha',
  'Sandra Cavalcante',
  'Santa Cruz',
  'Santa Rosa',
  'Santo Antônio',
  'São José',
  'Serrotão',
  'Tambor',
  'Três Irmãs',
  'Universitário',
  'Velame',
  'Vila Cabral',
] as const;
